// vehicles.ts

export const vehicles = {
  cars: [
    {
      id: 'shelby-gt350r',
      name: 'Shelby GT350R',
      price: '$60,900',
      image: 'https://media.gettyimages.com/id/1217483144/photo/2017-ford-mustang-shelby-gt350r.jpg?s=612x612&w=0&k=20&c=7OaqV_d1RYZDrNDp3AQXeertGHqlnLbfzfHmzBxr5mo=',
      category: 'performance',
      specs: {
        power: '526 HP',
        acceleration: '0-60 mph: 3.9s',
        topSpeed: 'Top Speed: 180 mph',
        engine: '5.2L V8',
        transmission: '6-speed manual',
        drivetrain: 'RWD',
        weight: '3,760 lbs',
        fuelEconomy: '14/21 mpg',
        year: '2017',
      },
      features: ['Track Ready', 'Recaro Seats', 'Brembo Brakes'],
    },
    {
      id: 'porsche-718-cayman',
      name: 'Porsche 718 Cayman',
      price: '$72,800',
      image: 'https://images.unsplash.com/photo-1592853625601-bb9d23da12fc?w=600&auto=format&fit=crop&q=60',
      category: 'luxury',
      specs: {
        power: '350 HP',
        acceleration: '0-60 mph: 4.0s',
        topSpeed: 'Top Speed: 177 mph',
        engine: '2.5L Turbo H4',
        transmission: '6-speed manual',
        drivetrain: 'RWD',
        weight: '3,040 lbs',
        fuelEconomy: '21/28 mpg',
        year: '2020',
      },
      features: ['Sport Chrono', 'Porsche Stability', 'Mid-Engine Balance'],
    },
    {
      id: 'dodge-hellcat',
      name: 'Dodge Challenger SRT Hellcat',
      price: '$79,000',
      image: 'https://vehicle-images.dealerinspire.com/6b82-110007511/2C3CDZC97GH198716/b20e9fc66915beaa3a69899e0bf3e798.jpg',
      category: 'performance',
      // category: 'Classic',
      specs: {
        power: '717 HP',
        acceleration: '0-60 mph: 3.4s',
        topSpeed: 'Top Speed: 199 mph',
        engine: '6.2L Supercharged V8',
        transmission: '8-speed auto',
        drivetrain: 'RWD',
        weight: '4,415 lbs',
        fuelEconomy: '13/22 mpg',
        year: '2019',
      },
      features: ['Supercharged Power', 'Launch Assist', 'Performance Tires'],
    },
    {
      id: 'mercedes-sls-amg',
      name: 'Mercedes-Benz SLS AMG',
      price: '$200,000',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mercedes-Benz_SLS_AMG_%28C_197%29_%E2%80%93_Frontansicht_ge%C3%B6ffnet%2C_10._August_2011%2C_D%C3%BCsseldorf.jpg/500px-Mercedes-Benz_SLS_AMG_%28C_197%29_%E2%80%93_Frontansicht_ge%C3%B6ffnet%2C_10._August_2011%2C_D%C3%BCsseldorf.jpg',
      category: 'luxury',
      specs: {
        power: '563 HP',
        acceleration: '0-60 mph: 3.7s',
        topSpeed: 'Top Speed: 197 mph',
        engine: '6.2L V8',
        transmission: '7-speed dual clutch',
        drivetrain: 'RWD',
        weight: '3,573 lbs',
        fuelEconomy: '14/20 mpg',
        year: '2011',
      },
      features: ['Gullwing Doors', 'Handcrafted Engine', 'Iconic Styling'],
    },
    {
      id: 'toyota-supra',
      name: 'Toyota GR Supra',
      price: '$76,500',
      image: 'https://static0.carbuzzimages.com/wordpress/wp-content/uploads/2024/03/972350-5.jpg',
      category: 'performance',
      specs: {
        power: '382 HP',
        acceleration: '0-60 mph: 3.9s',
        topSpeed: 'Top Speed: 155 mph',
        engine: '3.0L Turbo I6',
        transmission: '8-speed auto',
        drivetrain: 'RWD',
        weight: '3,397 lbs',
        fuelEconomy: '25 mpg',
        year: '2023',
      },
      features: ['BMW Platform', 'Adaptive Suspension', 'Digital Cockpit'],
    },
    {
      id: 'bmw-m5-ed35',
      name: 'BMW M5 Edition 35',
      price: '$117,495',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9FFsPq8AVmhk2a4cImaiLniyqWOdZA4JuXw&s',
      category: 'performance',
      specs: {
        power: '617 HP',
        acceleration: '0-60 mph: 3.1s',
        topSpeed: 'Top Speed: 190 mph',
        engine: '4.4L Twin-Turbo V8',
        transmission: '8-speed auto',
        drivetrain: 'AWD',
        weight: '4,345 lbs',
        fuelEconomy: '15/21 mpg',
        year: '2022',
      },
      features: ['xDrive AWD', 'Exclusive Trim', 'Track Mode'],
    },
    {
      id: 'corvette-c6',
      name: 'C6 Chevrolet Corvette',
      price: '$50,000',
      image: 'https://images.unsplash.com/photo-1629150631968-f4b17111acf3?q=80&w=2070&auto=format&fit=crop',
      category: 'performance',
      specs: {
        power: '430 HP',
        acceleration: '0-60 mph: 4.3s',
        topSpeed: 'Top Speed: 190 mph',
        engine: '6.2L V8',
        transmission: '6-speed manual',
        drivetrain: 'RWD',
        weight: '3,208 lbs',
        fuelEconomy: '16/26 mpg',
        year: '2013',
      },
      features: ['Lightweight', 'Targa Roof', 'American Muscle'],
    },
    {
      id: 'audi-r8',
      name: 'Audi R8',
      price: '$161,400',
      image: 'https://images.unsplash.com/photo-1590363719229-25b5e87b8983?w=600&auto=format&fit=crop&q=60',
      category: 'performance',
      specs: {
        power: '602 HP',
        acceleration: '0-60 mph: 3.3s',
        topSpeed: 'Top Speed: 205 mph',
        engine: '5.2L V10',
        transmission: '7-speed dual clutch',
        drivetrain: 'AWD',
        weight: '3,594 lbs',
        fuelEconomy: '13/20 mpg',
        year: '2021',
      },
      features: ['Quattro AWD', 'Virtual Cockpit', 'Carbon Sideblades'],
    },
    {
      id: 'porsche-918',
      name: 'Porsche 918 Spyder',
      price: '$164,200',
      image: 'https://lifebeyondsportmedia.com/bestanden/Porsche-918-Spyder/Porsche_spyder_800_x_600_1.jpg',
      category: 'performance',
      specs: {
        power: '887 HP',
        acceleration: '0-60 mph: 2.2s',
        topSpeed: 'Top Speed: 214 mph',
        engine: '4.6L V8 Hybrid',
        transmission: '7-speed dual clutch',
        drivetrain: 'AWD',
        weight: '3,602 lbs',
        fuelEconomy: '67 MPGe',
        year: '2015',
      },
      features: ['Hybrid Hypercar', 'Carbon Fiber Body', 'Regenerative Braking'],
    }
  ],
  bikes: [
    {
      id: 're-classic-350',
      name: 'Royal Enfield Classic 350',
      price: '$2,350',
      image: 'https://tse1.mm.bing.net/th?id=OIP.oB5E2gYbsxQ6MaItVsFEfAHaD4&pid=Api&P=0&h=180',
      category: 'cruiser',
      specs: {
        power: '20.2 HP',
        acceleration: '0-60 kmph: 6.5s',
        topSpeed: 'Top Speed: 114 kmph',
        engine: '349cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '195 kg',
        fuelEconomy: '35 km/l',
        year: '2023'
      },
      features: ['Classic Design', 'Reliable', 'Chrome Details']
    },
    {
      id: 're-hunter-350',
      name: 'Royal Enfield Hunter 350',
      price: '$1,780',
      image: 'https://tse1.mm.bing.net/th?id=OIP.bTLYndlyaAb0sZ4bulS28QAAAA&pid=Api&P=0&h=180',
      category: 'cruiser',
      specs: {
        power: '20.2 HP',
        acceleration: '0-60 kmph: 6.0s',
        topSpeed: 'Top Speed: 110 kmph',
        engine: '349cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '182 kg',
        fuelEconomy: '36 km/l',
        year: '2023'
      },
      features: ['Urban Style', 'Compact Frame', 'Agile Handling']
    },
    {
      id: 're-himalayan',
      name: 'Royal Enfield Himalayan',
      price: '$2,500',
      image: 'https://www.slashgear.com/img/gallery/5-royal-enfield-motorcycles-that-are-surprisingly-cheap/l-intro-1688247778.jpg',
      category: 'adventure',
      specs: {
        power: '24.3 HP',
        acceleration: '0-60 kmph: 5.9s',
        topSpeed: 'Top Speed: 120 kmph',
        engine: '411cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '199 kg',
        fuelEconomy: '30 km/l',
        year: '2023'
      },
      features: ['Adventure Ready', 'Long Travel Suspension', 'Off-road Grip']
    },
    {
      id: 're-classic-350-bobber',
      name: 'Royal Enfield Classic 350 Bobber',
      price: '$2,350',
      image: 'https://images.hindustantimes.com/auto/img/2022/11/01/1600x900/Royal_Enfield_Classic_350_Mighty_1667305460740_1667305468998_1667305468998.jpg',
      category: 'cruiser',
      specs: {
        power: '20.2 HP',
        acceleration: '0-60 kmph: 6.5s',
        topSpeed: 'Top Speed: 110 kmph',
        engine: '349cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '194 kg',
        fuelEconomy: '35 km/l',
        year: '2023'
      },
      features: ['Bobber Style', 'Low-Slung Seat', 'Solo Ride']
    },
    {
      id: 're-super-meteor-650',
      name: 'Royal Enfield Super Meteor 650',
      price: '$2,100',
      image: 'https://tse3.mm.bing.net/th?id=OIP.TKCU5nH_130YF5r9SsMIDgHaEs&pid=Api&P=0&h=180',
      category: 'cruiser',
      specs: {
        power: '47 HP',
        acceleration: '0-60 kmph: 5.1s',
        topSpeed: 'Top Speed: 160 kmph',
        engine: '648cc',
        transmission: '6-speed',
        drivetrain: 'Chain Drive',
        weight: '241 kg',
        fuelEconomy: '24 km/l',
        year: '2023'
      },
      features: ['Comfort Ride', 'Touring Ready', 'LED Lighting']
    },
    {
      id: 're-thunderbird-500x',
      name: 'Royal Enfield Thunderbird 500X',
      price: '$2,500',
      image: 'https://stat.overdrive.in/wp-content/odgallery/2018/04/42014_Royal_Enfield_Thunderbird_500X-2018-005.JPG',
      category: 'cruiser',
      specs: {
        power: '27.2 HP',
        acceleration: '0-60 kmph: 5.4s',
        topSpeed: 'Top Speed: 130 kmph',
        engine: '499cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '197 kg',
        fuelEconomy: '30 km/l',
        year: '2022'
      },
      features: ['Urban Tourer', 'Modern Looks', 'Alloy Wheels']
    },
    {
      id: 're-shotgun-650',
      name: 'Royal Enfield Shotgun 650',
      price: '$1,999',
      image: 'https://images.moneycontrol.com/static-mcnews/2024/01/Royal-Enfield-Shotgun-650-1.jpg?impolicy=website&width=1280&height=720',
      category: 'cruiser',
      specs: {
        power: '47 HP',
        acceleration: '0-60 kmph: 5.0s',
        topSpeed: 'Top Speed: 165 kmph',
        engine: '648cc',
        transmission: '6-speed',
        drivetrain: 'Chain Drive',
        weight: '240 kg',
        fuelEconomy: '26 km/l',
        year: '2024'
      },
      features: ['Neo-Retro Vibe', 'Unique Styling', 'Parallel Twin']
    },
    {
      id: 're-thunderbird-commuter',
      name: 'Royal Enfield Thunderbird 500X (Commuter)',
      price: '$2,250',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ94gjDDqHomsODQAiu7mPWQ6OMV-ylwgn6-w&s',
      category: 'cruiser',
      specs: {
        power: '27.2 HP',
        acceleration: '0-60 kmph: 5.4s',
        topSpeed: 'Top Speed: 130 kmph',
        engine: '499cc',
        transmission: '5-speed',
        drivetrain: 'Chain Drive',
        weight: '197 kg',
        fuelEconomy: '30 km/l',
        year: '2022'
      },
      features: ['Sleek Commuter', 'Comfort Seat', 'Dual Tone Paint']
    }
  ]
};

